name: movieapp
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase: ^9.0.1
  firebase_auth: ^3.0.1
  provider: ^5.0.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  google_sign_in: ^5.0.7
  firebase_core: ^1.4.0
  path_provider: ^2.0.2
  dartz: ^0.10.0
  bloc: ^7.0.0
  flutter_bloc: ^7.1.0
  freezed_annotation: ^0.14.2
  injectable: ^1.4.1
  uuid: ^3.0.4
  get_it: ^7.2.0
  auto_route: ^2.3.0
  another_flushbar: ^1.10.22
  flutter_hooks: ^0.18.0
  image_picker: ^0.8.3+2
  
dev_dependencies:
  injectable_generator: ^1.4.1
  auto_route_generator: ^2.1.0
  hive_generator: ^1.1.0
  build_runner: ^2.1.1
  freezed: ^0.14.2
  lint: ^1.5.3
  
flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/icons/